version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'gstportfoliodb'
      MYSQL_ROOT_PASSWORD: 'projetoxp'
    ports:
      - '3306:3306'
    expose:
      - '3306'

